steps:
  - name: 'docker.io/library/python:3.7'
    entrypoint: /bin/sh
    # Run pip install and pytest in the same build step
    # (pip packages won't be preserved in future steps!)
    args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
    dir: 'functions/id/get'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'user_handler', '--runtime=python37', '--trigger-http', '--region=europe-west1']
    dir: 'functions/id/get'

  - name: 'docker.io/library/python:3.7'
    entrypoint: /bin/sh
    # Run pip install and pytest in the same build step
    # (pip packages won't be preserved in future steps!)
    args: [-c, 'pip install -r requirements.txt', '&&', 'pytest']
    dir: 'functions/all'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'users_handler', '--runtime=python37', '--trigger-http', '--region=europe=west1']
    dir: 'functions/all'